echo "build project using cmake"
echo "you can specify compilers (clang/clang++ or gcc/g++)"
echo "and build system (Ninja or Unix Makefiles)"
echo "made by vertoker"
echo "--------------------------"

echo "First of all, script needs to know C and C++ compilers you want to use"
echo "Enter C compiler you want to use (clang, gcc) (example: clang)"
read CCompiler
echo "Enter C++ compiler you want to use (clang++, g++) (example: clang++)"
read CppCompiler

echo "Next where build will be located"
echo "Enter path to the build folder (example: ./out/)"
read BuildFolder

echo "Next enter cmake generator you want to use ('Ninja' or 'Unix Makefiles')"
echo "Enter cmake generator you want to use (example: Ninja)"
read BuildGenerator

echo "Next enter build system for building generated by cmake files"
echo "(for 'Ninja' - ninja, for 'Unix Makefiles' - make)"
echo "Enter build system for generated files (example: ninja)"
read BuildSystem

echo "Next enter build type for executable will be (Debug or Release)"
echo "Enter build type (example: Debug)"
read BuildType

echo "--------------------------"

mkdir $BuildFolder
cd $BuildFolder

cmake .. -DCMAKE_BUILD_TYPE="$BuildType" -DCMAKE_C_COMPILER="$CCompiler" -DCMAKE_CXX_COMPILER="$CppCompiler" -G "$BuildGenerator"
$BuildSystem
./executable

